from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.n_f_Button = QtWidgets.QPushButton(self.centralwidget)
        self.n_f_Button.setGeometry(QtCore.QRect(11, 37, 93, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.n_f_Button.setFont(font)
        self.n_f_Button.setObjectName("n_f_Button")
        self.n_f_Button.setStyleSheet("QPushButton::hover"
                             "{"
                             "background-color : Khaki;"
                             "}")
        self.n_f_label = QtWidgets.QLabel(self.centralwidget)
        self.n_f_label.setGeometry(QtCore.QRect(60, 10, 256, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.n_f_label.setFont(font)
        self.n_f_label.setObjectName("n_f_label")
        self.n_f_art_lable = QtWidgets.QLabel(self.centralwidget)
        self.n_f_art_lable.setGeometry(QtCore.QRect(491, 37, 44, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.n_f_art_lable.setFont(font)
        self.n_f_art_lable.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.n_f_art_lable.setObjectName("n_f_art_lable")
        self.n_f_price_lable = QtWidgets.QLabel(self.centralwidget)
        self.n_f_price_lable.setGeometry(QtCore.QRect(580, 37, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.n_f_price_lable.setFont(font)
        self.n_f_price_lable.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.n_f_price_lable.setObjectName("n_f_price_lable")
        self.n_f_table = QtWidgets.QTableWidget(self.centralwidget)
        self.n_f_table.setGeometry(QtCore.QRect(11, 84, 1231, 210))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.n_f_table.setFont(font)
        self.n_f_table.setObjectName("n_f_table")
        self.n_f_table.setColumnCount(0)
        self.n_f_table.setRowCount(0)
        self.n_f_path = QtWidgets.QLineEdit(self.centralwidget)
        self.n_f_path.setGeometry(QtCore.QRect(111, 37, 376, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.n_f_path.setFont(font)
        self.n_f_path.setText("")
        self.n_f_path.setReadOnly(True)
        self.n_f_path.setObjectName("n_f_path")
        self.n_f_path.setStyleSheet("QLineEdit::hover"
                                      "{"
                                      "background-color : Khaki;"
                                      "}")
        self.n_f_art_value = QtWidgets.QLineEdit(self.centralwidget)
        self.n_f_art_value.setGeometry(QtCore.QRect(540, 37, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.n_f_art_value.setFont(font)
        self.n_f_art_value.setObjectName("n_f_art_value")
        self.n_f_art_value.setStyleSheet("QLineEdit::hover"
                                      "{"
                                      "background-color : Khaki;"
                                      "}")
        self.n_f_price_value = QtWidgets.QLineEdit(self.centralwidget)
        self.n_f_price_value.setGeometry(QtCore.QRect(670, 37, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.n_f_price_value.setFont(font)
        self.n_f_price_value.setObjectName("n_f_price_value")
        self.n_f_price_value.setStyleSheet("QLineEdit::hover"
                                      "{"
                                      "background-color : Khaki;"
                                      "}")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(1, 300, 1248, 2))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.o_f_art_value = QtWidgets.QLineEdit(self.centralwidget)
        self.o_f_art_value.setGeometry(QtCore.QRect(540, 340, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.o_f_art_value.setFont(font)
        self.o_f_art_value.setObjectName("o_f_art_value")
        self.o_f_art_value.setStyleSheet("QLineEdit::hover"
                                      "{"
                                      "background-color : Khaki;"
                                      "}")
        self.o_f_price_lable = QtWidgets.QLabel(self.centralwidget)
        self.o_f_price_lable.setGeometry(QtCore.QRect(580, 340, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.o_f_price_lable.setFont(font)
        self.o_f_price_lable.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.o_f_price_lable.setObjectName("o_f_price_lable")
        self.o_f_art_lable = QtWidgets.QLabel(self.centralwidget)
        self.o_f_art_lable.setGeometry(QtCore.QRect(491, 340, 46, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.o_f_art_lable.setFont(font)
        self.o_f_art_lable.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.o_f_art_lable.setObjectName("o_f_art_lable")
        self.o_f_path = QtWidgets.QLineEdit(self.centralwidget)
        self.o_f_path.setGeometry(QtCore.QRect(111, 340, 376, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.o_f_path.setFont(font)
        self.o_f_path.setReadOnly(True)
        self.o_f_path.setObjectName("o_f_path")
        self.o_f_path.setStyleSheet("QLineEdit::hover"
                                      "{"
                                      "background-color : Khaki;"
                                      "}")
        self.o_f_Button = QtWidgets.QPushButton(self.centralwidget)
        self.o_f_Button.setGeometry(QtCore.QRect(11, 340, 93, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.o_f_Button.setFont(font)
        self.o_f_Button.setObjectName("o_f_Button")
        self.o_f_Button.setStyleSheet("QPushButton::hover"
                                      "{"
                                      "background-color : Khaki;"
                                      "}")
        self.o_f_table = QtWidgets.QTableWidget(self.centralwidget)
        self.o_f_table.setGeometry(QtCore.QRect(11, 387, 1231, 210))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.o_f_table.setFont(font)
        self.o_f_table.setObjectName("o_f_table")
        self.o_f_table.setColumnCount(0)
        self.o_f_table.setRowCount(0)
        self.o_f_price_value = QtWidgets.QLineEdit(self.centralwidget)
        self.o_f_price_value.setGeometry(QtCore.QRect(670, 340, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.o_f_price_value.setFont(font)
        self.o_f_price_value.setObjectName("o_f_price_value")
        self.o_f_price_value.setStyleSheet("QLineEdit::hover"
                                      "{"
                                      "background-color : Khaki;"
                                      "}")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(1, 600, 1248, 5))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.o_f_label = QtWidgets.QLabel(self.centralwidget)
        self.o_f_label.setGeometry(QtCore.QRect(60, 313, 256, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.o_f_label.setFont(font)
        self.o_f_label.setObjectName("o_f_label")
        self.o_f_new_price_value = QtWidgets.QLineEdit(self.centralwidget)
        self.o_f_new_price_value.setGeometry(QtCore.QRect(850, 340, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.o_f_new_price_value.setFont(font)
        self.o_f_new_price_value.setObjectName("o_f_new_price_value")
        self.o_f_new_price_value.setStyleSheet("QLineEdit::hover"
                                      "{"
                                      "background-color : Khaki;"
                                      "}")
        self.o_f_new_price_lable = QtWidgets.QLabel(self.centralwidget)
        self.o_f_new_price_lable.setGeometry(QtCore.QRect(710, 340, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.o_f_new_price_lable.setFont(font)
        self.o_f_new_price_lable.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.o_f_new_price_lable.setObjectName("o_f_new_price_lable")
        self.result_Button = QtWidgets.QPushButton(self.centralwidget)
        self.result_Button.setGeometry(QtCore.QRect(11, 606, 377, 109))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.result_Button.setFont(font)
        self.result_Button.setObjectName("result_Button")
        self.result_Button.setStyleSheet("QPushButton::hover"
                                      "{"
                                      "background-color : Khaki;"
                                      "}")
        self.result_table = QtWidgets.QTableWidget(self.centralwidget)
        self.result_table.setGeometry(QtCore.QRect(400, 606, 479, 369))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.result_table.setFont(font)
        self.result_table.setObjectName("result_table")
        self.result_table.setColumnCount(0)
        self.result_table.setRowCount(0)
        self.result_text = QtWidgets.QTextEdit(self.centralwidget)
        self.result_text.setGeometry(QtCore.QRect(880, 606, 369, 369))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.result_text.setFont(font)
        self.result_text.setObjectName("result_text")
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font = QtGui.QFont()
        font.setPointSize(10)
        font = QtGui.QFont()
        font.setPointSize(10)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.del_excess = QtWidgets.QPushButton(self.centralwidget)
        self.del_excess.setGeometry(QtCore.QRect(11, 750, 156, 56))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.del_excess.setFont(font)
        self.del_excess.setObjectName("del_excess")
        self.del_excess.setStyleSheet("QPushButton::hover"
                                      "{"
                                      "background-color : Khaki;"
                                      "}")
        self.del_repeat_single = QtWidgets.QPushButton(self.centralwidget)
        self.del_repeat_single.setGeometry(QtCore.QRect(11, 820, 156, 56))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.del_repeat_single.setFont(font)
        self.del_repeat_single.setObjectName("del_repeat_single")
        self.del_repeat_single.setStyleSheet("QPushButton::hover"
                                      "{"
                                      "background-color : Khaki;"
                                      "}")
        self.del_repeat_single_sum = QtWidgets.QPushButton(self.centralwidget)
        self.del_repeat_single_sum.setGeometry(QtCore.QRect(235, 820, 156, 56))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.del_repeat_single_sum.setFont(font)
        self.del_repeat_single_sum.setObjectName("del_repeat_single_sum")
        self.del_repeat_single_sum.setStyleSheet("QPushButton::hover"
                                      "{"
                                      "background-color : Khaki;"
                                      "}")
        self.del_repeat_items = QtWidgets.QPushButton(self.centralwidget)
        self.del_repeat_items.setGeometry(QtCore.QRect(235, 750, 156, 56))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.del_repeat_items.setFont(font)
        self.del_repeat_items.setObjectName("del_repeat_items")
        self.del_repeat_items.setStyleSheet("QPushButton::hover"
                                      "{"
                                      "background-color : Khaki;"
                                      "}")
        self.nf_start_row_lable = QtWidgets.QLabel(self.centralwidget)
        self.nf_start_row_lable.setGeometry(QtCore.QRect(790, 37, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nf_start_row_lable.setFont(font)
        self.nf_start_row_lable.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nf_start_row_lable.setObjectName("nf_start_row_lable")
        self.nf_start_row_value = QtWidgets.QLineEdit(self.centralwidget)
        self.nf_start_row_value.setGeometry(QtCore.QRect(880, 37, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nf_start_row_value.setFont(font)
        self.nf_start_row_value.setObjectName("nf_start_row_value")
        self.nf_start_row_value.setStyleSheet("QLineEdit::hover"
                                      "{"
                                      "background-color : Khaki;"
                                      "}")
        self.of_start_row_value = QtWidgets.QLineEdit(self.centralwidget)
        self.of_start_row_value.setGeometry(QtCore.QRect(1110, 340, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.of_start_row_value.setFont(font)
        self.of_start_row_value.setObjectName("of_start_row_value")
        self.of_start_row_value.setStyleSheet("QLineEdit::hover"
                                      "{"
                                      "background-color : Khaki;"
                                      "}")
        self.of_start_row_lable = QtWidgets.QLabel(self.centralwidget)
        self.of_start_row_lable.setGeometry(QtCore.QRect(1020, 340, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.of_start_row_lable.setFont(font)
        self.of_start_row_lable.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.of_start_row_lable.setObjectName("of_start_row_lable")
        self.nf_sheet_value = QtWidgets.QLineEdit(self.centralwidget)
        self.nf_sheet_value.setGeometry(QtCore.QRect(780, 37, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nf_sheet_value.setFont(font)
        self.nf_sheet_value.setObjectName("nf_sheet_value")
        self.nf_sheet_value.setStyleSheet("QLineEdit::hover"
                                      "{"
                                      "background-color : Khaki;"
                                      "}")
        self.nf_sheet_lable = QtWidgets.QLabel(self.centralwidget)
        self.nf_sheet_lable.setGeometry(QtCore.QRect(720, 37, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nf_sheet_lable.setFont(font)
        self.nf_sheet_lable.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nf_sheet_lable.setObjectName("nf_sheet_lable")
        self.of_sheet_value = QtWidgets.QLineEdit(self.centralwidget)
        self.of_sheet_value.setGeometry(QtCore.QRect(1010, 340, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.of_sheet_value.setFont(font)
        self.of_sheet_value.setObjectName("of_sheet_value")
        self.of_sheet_value.setStyleSheet("QLineEdit::hover"
                                      "{"
                                      "background-color : Khaki;"
                                      "}")
        self.of_sheet_lable = QtWidgets.QLabel(self.centralwidget)
        self.of_sheet_lable.setGeometry(QtCore.QRect(950, 340, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.of_sheet_lable.setFont(font)
        self.of_sheet_lable.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.of_sheet_lable.setObjectName("of_sheet_lable")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PriceCheckerBalon"))
        self.n_f_Button.setText(_translate("MainWindow", "Выбрать"))
        self.n_f_label.setText(_translate("MainWindow", "Файл с данными"))
        self.n_f_art_lable.setText(_translate("MainWindow", "Код"))
        self.n_f_price_lable.setText(_translate("MainWindow", "Значение"))
        self.o_f_price_lable.setText(_translate("MainWindow", "Значение"))
        self.o_f_art_lable.setText(_translate("MainWindow", "Код"))
        self.o_f_Button.setText(_translate("MainWindow", "Выбрать"))
        self.o_f_label.setText(_translate("MainWindow", "Файл для обработки"))
        self.o_f_new_price_lable.setText(_translate("MainWindow", "Новое значение"))
        self.result_Button.setText(_translate("MainWindow", "Сравнить"))
        self.del_excess.setText(_translate("MainWindow", "Удалить лишние"))
        self.del_repeat_single.setText(_translate("MainWindow", "Дубли в одной"))
        self.del_repeat_single_sum.setText(_translate("MainWindow", "Дубли в одной+"))
        self.del_repeat_items.setText(_translate("MainWindow", "Удалить дубли"))
        self.nf_start_row_lable.setText(_translate("MainWindow", "Строка"))
        self.nf_start_row_value.setText(_translate("MainWindow", "2"))
        self.of_start_row_value.setText(_translate("MainWindow", "2"))
        self.of_start_row_lable.setText(_translate("MainWindow", "Строка"))
        self.nf_sheet_value.setText(_translate("MainWindow", "1"))
        self.nf_sheet_lable.setText(_translate("MainWindow", "Лист"))
        self.of_sheet_value.setText(_translate("MainWindow", "1"))
        self.of_sheet_lable.setText(_translate("MainWindow", "Лист"))
